# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StressSensorApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  inhibit_all_warnings!

  # Pods for StressSensorApp
  pod 'Charts'
  pod 'Firebase', '4.3.0'
  pod 'Firebase/Core', '4.3.0'
  pod 'Firebase/Database', '4.3.0'
  pod 'Firebase/Auth', '4.3.0'
  pod 'ResearchKit', '~> 1.0'
  pod 'ReSwift', '~> 4.0.1'
  pod 'PromiseKit', '~> 6.8'
  pod 'Eureka'

  target 'StressSensorAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StressSensorAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
