# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StressSensorApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  inhibit_all_warnings!

  # Pods for StressSensorApp
  pod 'Charts'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'ResearchKit', '~> 1.0'

  target 'StressSensorAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StressSensorAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
